### ISSUE TITLE
UraniumUI controls not working anymore with dotnet/maui version shipped with Visual Studio 17.5.4

### ISSUE THREAD

**Issue by StepKie** [enisn/UraniumUI#281]
After upgrading Visual Studio, material controls like TextField, EditorField, DateField, Picker etc. do not work anymore. They work fine when using VS 17.5.3

**Comment by enisn** [comment]
Latest version is based on MAUI 7.0.58, 

If you define maui version in csproj like below, it should be working well. I'll update to the latest maui version soon
```xml
<MauiVersion>7.0.58</MauiVersion>
```

**Comment by enisn** [comment]
I'm using currently Visual Studio 17.6.0 Preview 3.0 version. When you define Maui version of project in the csproj, the IDE will use that version to run the application. I'll update as soon as possible to the latest version
<img width="380" alt="image" src="https://user-images.githubusercontent.com/23705418/231879648-f062c1cf-cc2e-4336-a58b-0d8290da81d6.png">

**Comment by joshsutterfield** [comment]
Was there something in particular about this Maui update? I assume most updates would not require every Maui project to point to that version, right? Windows Update appears to have updated my .net 7 version and Maui along with it, even without having updated Visual Studio itself, and kablam, text fields etc. gone wonky. Thanks for the followup - for now I'll lock in my MauiVersion as advised.

**Comment by StepKie** [comment]
> for now I'll lock in my MauiVersion as advised.





> Latest version is based on MAUI 7.0.58,
> 
> If you define maui version in csproj like below, it should be working well. I'll update to the latest maui version soon
> 
> ```
> <MauiVersion>7.0.58</MauiVersion>
> ```

Posting to confirm this workaround alleviated the issue for me.
If you find out, I'd be interested if you can share with us the results of the post-mortem (i.e. how the .NET update was able to break your package...)

Thanks for quickly providing the temporary fix!

**Comment by get-flat** [comment]
FYI: https://github.com/dotnet/maui/issues/4812#issuecomment-1075583594

**Comment by enisn** [comment]
UraniumUI Version 2.4 is based on Maui 7.0.81, so you can upgrade to 2.4

https://github.com/enisn/UraniumUI/releases/tag/v2.4.0

**Comment by get-flat** [comment]
@enisn do you suggest it should now work without \<MauiVersion\>?
> UraniumUI Version 2.4 is based on Maui 7.0.81, so you can upgrade to 2.4

I use material TextField/Pickers inside inputkit FormView (unfortunately still doesn't work)
UraniumUI.Material 2.4.0
InputKit.Maui 4.2.9
VS 17.5.4

**Comment by enisn** [comment]
InputKit was compiled with Maui 7.0.52 SDK. So, I just updated all the dependencies, it should be fixed in v2.4.1

**Comment by cwilde123** [comment]
Not sure I tried upgrading to uranium nuget version 2.4.1 and applied MAUI version 7.0.81 in csproj but I still get that text fields and such are empty and cant be clicked upon etc. Uranium 2.3.3 with maui 7.0.58 in csproj worked ok. Is there anything else I need to do?

**Comment by enisn** [comment]
Yeah, I reproduced the problem. It seems it happens on Android and partly on windows. 

It works properly on iOS and Maccatalyst. I'll patch a release for them. Some handler behaviors seem changed.

**Comment by ProgramadorPmc2** [comment]
Hi, I'm using DataGrid in my project and I have updated already to 2.4.1 but the DataGrid isn't working.

This is before the bug, It's Ok
![DataGrid 17 5 3](https://user-images.githubusercontent.com/125761477/232811483-e4dbdef4-2481-414e-a4a6-1b52469d84e8.PNG)

I have the bug when I updated VS to 17.5.4 while I had Uranium UI 2.3.3
![DataGrid 17 5 4](https://user-images.githubusercontent.com/125761477/232811487-dac12f94-8584-4436-bd3a-977e32979adf.PNG)

**Comment by enisn** [comment]
> Hi, I'm using DataGrid in my project and I have updated already to 2.4.1 but the DataGrid isn't working.
> 
> This is before the bug, It's Ok ![DataGrid 17 5 3](https://user-images.githubusercontent.com/125761477/232811483-e4dbdef4-2481-414e-a4a6-1b52469d84e8.PNG)
> 
> I have the bug when I updated VS to 17.5.4 while I had Uranium UI 2.3.3 ![DataGrid 17 5 4](https://user-images.githubusercontent.com/125761477/232811487-dac12f94-8584-4436-bd3a-977e32979adf.PNG)

It might be related to this https://github.com/dotnet/maui/pull/13523 and https://github.com/dotnet/maui/pull/13523

Grid calculations are completely changed in the new version of maui

**Comment by enisn** [comment]
Unfortunately, Grid behaves differently on each platform. so I couldn't find a common solution that works on each platform.

I have created an issue about it.
https://github.com/dotnet/maui/issues/14645

**Comment by enisn** [comment]
Sorry guys, I tried a lot of things and finally found a simple workaround for the latest strange Grid behavior.

This PR https://github.com/enisn/UraniumUI/pull/294 includes a workaround for grid that can't calculate height on Android & windows currently. So I assigned a hard-coded number as HeightRequest. If you use different label sizes, still some problems may occur but at least default configuration works for now.

**Comment by enisn** [comment]
Hi @ProgramadorPmc2 
You can set a HeightRequest for your DataGrid cells. It can't be dynamically calculated by Grid currently.

**Comment by ketakidevendra** [comment]
@enisn I am facing same issue again after upgrading VS 17.5.5 in iOS. Controls stopped working in iOS.
It works fine in android.

**Comment by enisn** [comment]
Microsoft seems backported the Grid issue fix to .NET 7 instead awaiting .Net8 release: https://github.com/dotnet/maui/pull/14165

Your DataGrid issue should be solved too @ProgramadorPmc2 
Just update your workloads `dotnet workload update` and set MauiVersion as `7.0.86` if you have that tag in your csproj

**Comment by ketakidevendra** [comment]
Great. Thank you for investigation.

Regards,
Ketaki

**Comment by enisn** [comment]
Microsoft released a patch for this issue, so this problem won't be happening on the `7.0.86` and newer versions

https://github.com/dotnet/maui/releases/tag/7.0.86
