### ISSUE TITLE
TextField RequiredValidation throw XFC0009 when build

### ISSUE THREAD

**Issue by MercuryVN** [enisn/UraniumUI#413]
What I did:
1. Create a fresh new project
2. Install InputKit.Maui and UraniumUI.Material
3. Add `.UseUraniumUI().UseUraniumUIMaterial().ConfigureMauiHandlers(handlers => handlers.AddInputKitHandlers())` to MauiProgram.cs
4. Change the MainPage.xaml to the following:
```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
                        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
			xmlns:material="http://schemas.enisn-projects.io/dotnet/maui/uraniumui/material"
			xmlns:validation="clr-namespace:InputKit.Shared.Validations;assembly=InputKit.Maui"
                        x:Class="TestApp.MainPage">

	<VerticalStackLayout>

		<material:TextField x:Name="TestTextField"
                                               Title="Test Validation">

			<material:TextField.Validations>

				<validation:RequiredValidation />

			</material:TextField.Validations>

		</material:TextField>

	</VerticalStackLayout>

</ContentPage>
```

5.  Build

The error throw: XFC0009 No property, BindableProperty, or event found for "Validations", or mismatching type between value and property.

If I don't use Validations in xaml and instead put `TestTextField.Validations.Add(new RequiredValidation());` in my code-behind, it builds and works normally

If I add `<validation:MinLengthValidation MinLength="0" />` inside the `<material:TextField.Validations>` it also builds and works normally but I don't think this is what it is intended to be and is my current workaround.

If I don't put anything under `<material:TextField.Validations>` and run, then add `<validation:RequiredValidation />` to it and hot reload, it works correctly but when I stop the program and rebuild, the error throw again

**Comment by enisn** [comment]
TextField defines `Validations` as content property and it should be working when you directly define validations inside TextField node.
https://github.com/enisn/UraniumUI/blob/45f8dbcba5492305ac3a64cbfe29d93515926198/src/UraniumUI.Material/Controls/TextField.cs#L12

This usage is working on me and Build Pipeline as well. If your compiler couldn't recognize it, please make sure your Visual Studio is on the latest version and try updating maui workloads with command: `dotnet workload update`

**Comment by MercuryVN** [comment]
> This usage is working on me and Build Pipeline as well. If your compiler couldn't recognize it, please make sure your Visual Studio is on the latest version and try updating maui workloads with command: `dotnet workload update`

I have tried to uppdate my VS to latest version 17.6.5, the InputKit and UraniumUI package to latest version and try `dotnet workload update` but the problem still persists

**Comment by enisn** [comment]
I saw an existing issue on dotnet/maui repo
https://github.com/dotnet/maui/issues/15061

**Comment by ccgould** [comment]
This issue isn't in version 4.3.4 of InputKit  but it is present in 4.3.5

**Comment by enisn** [comment]
> This issue isn't in version 4.3.4 of InputKit but it is present in 4.3.5

That makes sense, thank you for your detection, UraniumUI doesn't have reference to the latest InputKit, if you separately use InputKit, this might happen. You can try removing InputKit reference from **csproj** file and use UraniumUI referenced version instead.

I'll release another version that depends on the latest version soon
